---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - exposer.netlops.com
  resources:
  - balancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - exposer.netlops.com
  resources:
  - balancers/finalizers
  verbs:
  - update
- apiGroups:
  - exposer.netlops.com
  resources:
  - balancers/status
  verbs:
  - get
  - patch
  - update
