apiVersion: exposer.netlops.com/v1alpha1
kind: Balancer
metadata:
  name: balancer-example
spec:
  ports:
    # This is a frontend service for handling all input requests.
    # Thus, the targetPort is the port exposed by the target backend containers.
    - name: http
      port: 80
      targetPort: 5678
  selector:
    # for selecting a group of related backends
    app: test
  backends:
    - name: v1
      weight: 40
      selector:
        # for selecting a group of related backends
        version: v1
    - name: v2
      weight: 20
      selector:
        # for selecting a group of related backends
        version: v2
    - name: v3
      weight: 40
      selector:
        # for selecting a group of related backends
        version: v3